/*
 * generated by Xtext
 */
package fr.supelec.tesl.lang.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import fr.supelec.tesl.lang.services.TESLGrammarAccess;

public class TESLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private TESLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected fr.supelec.tesl.lang.parser.antlr.internal.InternalTESLParser createParser(XtextTokenStream stream) {
		return new fr.supelec.tesl.lang.parser.antlr.internal.InternalTESLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Specification";
	}
	
	public TESLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TESLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
