/*
 * generated by Xtext
 */
package fr.supelec.tesl.lang;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class TESLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return fr.supelec.tesl.lang.ui.internal.TESLActivator.getInstance().getInjector("fr.supelec.tesl.lang.TESL");
	}

}
