/**
 * generated by Xtext
 */
package fr.supelec.tesl.lang.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
public class TESLProposalProvider extends AbstractTESLProposalProvider {
}
