/*
 * generated by Xtext
 */
package fr.supelec.tesl.lang.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TESLUiModule extends fr.supelec.tesl.lang.ui.AbstractTESLUiModule {
	public TESLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
