/**
 * generated by Xtext
 */
package fr.supelec.tesl.lang.ui.outline;

import org.eclipse.swt.graphics.Image;
import org.eclipse.xtext.ui.editor.outline.IOutlineNode;
import org.eclipse.xtext.ui.editor.outline.impl.AbstractOutlineNode;

public class VirtualOutlineNode extends AbstractOutlineNode {
  protected VirtualOutlineNode(final IOutlineNode parent, final Image image, final /* Object */Object text, final boolean isLeaf) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method super(IOutlineNode, Image, Object, boolean) is undefined");
  }
}
