/**
 * generated by Xtext
 */
package fr.supelec.tesl.lang.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
public class TESLQuickfixProvider extends DefaultQuickfixProvider {
}
