/*
 * generated by Xtext
 */
package fr.supelec.tesl.lang;

import org.eclipse.xtext.conversion.IValueConverterService;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TESLRuntimeModule extends fr.supelec.tesl.lang.AbstractTESLRuntimeModule {
    @Override
    public Class<? extends IValueConverterService> 
        bindIValueConverterService() {
        return TESLValueConverterService.class;
    }
}
