/*
* generated by Xtext
*/
package fr.supelec.tesl.lang;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class TESLStandaloneSetup extends TESLStandaloneSetupGenerated{

	public static void doSetup() {
		new TESLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

