/*
 * generated by Xtext
 */
package fr.supelec.tesl.lang.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import fr.supelec.tesl.lang.ui.internal.TESLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TESLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TESLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TESLActivator.getInstance().getInjector(TESLActivator.FR_SUPELEC_TESL_LANG_TESL);
	}
	
}
