/**
 * generated by Xtext
 */
package fr.supelec.tesl.lang.validation;

import fr.supelec.tesl.lang.tesl.Clock;
import fr.supelec.tesl.lang.tesl.ImplicationQualifier;
import fr.supelec.tesl.lang.tesl.ImplicationRelation;
import fr.supelec.tesl.lang.tesl.TeslPackage;
import fr.supelec.tesl.lang.tesl.TimeDelayedQualifier;
import java.util.Objects;
import org.eclipse.xtext.validation.Check;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class TESLValidator extends AbstractTESLValidator {
  @Check
  public Object checkClockDoesNotImplyItself(final ImplicationRelation r) {
    Object _xifexpression = null;
    ImplicationQualifier _qual = r.getQual();
    if ((_qual instanceof TimeDelayedQualifier)) {
      _xifexpression = null;
    } else {
      Clock _source = r.getSource();
      Clock _target = r.getTarget();
      boolean _equals = Objects.equals(_source, _target);
      if (_equals) {
        this.error("Clock implies itself", r, TeslPackage.Literals.IMPLICATION_RELATION__TARGET);
      }
    }
    return _xifexpression;
  }
}
