/*
 * generated by Xtext
 */
package fr.supelec.tesl.lang.ui.contentassist

import fr.supelec.tesl.lang.ui.contentassist.AbstractTESLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class TESLProposalProvider extends AbstractTESLProposalProvider {
}
